[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metabolic_app"
version = "0.1.0"
description = "Aplicación de análisis metabólico"
requires-python = ">=3.8"

[tool.pytest.ini_options]
pythonpath = [
    "."
] 